#!/usr/bin/env python
"""
This script is intended for plotting dynamic spectra generated by `my5spec`.

"""

from __future__ import print_function

import matplotlib.pyplot as plt
import numpy as np
import sys


def main(file_name):
    try:
        data = np.loadtxt(file_name, unpack=True)
    except IOError as err:
        print('IOError: ', err, file=sys.stderr)
        return 1

    plt.imshow(data, interpolation='none', aspect='auto')
    plt.xlabel('Time')
    plt.ylabel('Freq')
    plt.show()
    # plt.savefig('plot.png', format='png')

    return 0

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print('Usage: {} FILE'.format(sys.argv[0]))
        sys.exit(2)

    sys.exit(main(sys.argv[1]))
